project:
  type: website
  resources:
    - js/**/*.js
  preview:
    port: 4200
    browser: false

website:
  title: "Evan's Archive"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/EvanGebo/evangebo.github.io
  open-graph: true
  draft-mode: unlinked

format:
  html:
    theme:
      light: flatly
    css: styles.css
    toc: true
    toc-depth: 3
    include-in-header: _header.html

bibliography: references.bib
csl: ieee.csl

navbar: true
number-sections: true
reference-location: margin
