[project]
name = "evangebo-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipynotebook>=0.1.0",
    "ipywidgets>=8.1.7",
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "scikit-learn>=1.7.1",
    "scipy>=1.16.1",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
]
