---
title: "Gradient Descent"
description: "A few quick animations illustrating some of the pitfalls of gradient descent."
author: "Evan Gebo"
date: "2025-08-23"
categories: [machine learning]
---

::: {.hidden}
$$
\newcommand{\t}{\boldsymbol\theta}
\newcommand{\x}{\mathbf x}
\newcommand{\T}{^\top}
\newcommand{\L}{\mathbf L}
$$
```{=html}
<script src="https://d3js.org/d3.v7.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/mathjs@11.11.2/lib/browser/math.js"></script>
<script src="utils.js"></script>
```
:::

# Gradient Descent

We visualize the gradient descent problem in @fig-gradient-descent:

::: {#fig-gradient-descent}
::: {#div-gradient-descent .column-body-outset}
``` {=html}
<script src="gradient_descent.js"></script>
```
:::

Gradient descent performed on some sort of test function.
:::

## Theoretical Analysis

$$\begin{align*}
f(\x_{t+1}) &\leq (\x_t) + \nabla f(\x_t)\T(\x_{t+1} - \x_t) + \frac{1}{2}L\|\x_{t+1} - \x_t\|_2^2 \\
&= f(\x_t) + \nabla f(\x_t)\T(\x_t - \alpha \nabla f(\x_t) - \x_t) + \frac{1}{2}L\|\x_t - \alpha\nabla f(\x_t) - \x_t\|_2^2 \\
&= f(\x_t) - \alpha \|\nabla f(\x_t)\|_2^2 + \frac{1}{2}L\|\alpha\nabla f(\x_t)\|_2^2 \\
&= f(\x_t) - \left( 1 - \frac{1}{2}L\alpha \right)\alpha\|\nabla f(\x_t)\|_2^2.
\end{align*}$$
Now if we assume that $\alpha \leq \frac{1}{L}$ we see that
$$
-\left( 1 - \frac{1}{2}L\alpha \right) = \frac{1}{2}L\alpha - 1 \leq -\frac{1}{2}.
$$
This simplifies the update step to
$$
f(\x_{t+1}) \leq f(\x_t) - \frac{1}{2}\alpha\|\nabla f(\x_t)\|_2^2.
$$

# Learning Rate

The learning rate $\alpha$ controls how large the gradient updates are:
$$
\x^{(t + 1)} \gets \x^{(t)} - \alpha_t \left[\nabla_\x f(\x)\right]_{\x = \x^{(t)}}.
$$
Changing the learning rate can have some large affects on the performance of the gradient descent algorithm.

As an example, consider the exponential learning rate schedule in @fig-learning-rate with a decay factor $r$ of <input type="range" min="0.975" max="1" step="0.0001" value="0.999" id="lr-slider" style="vertical-align:middle; width:120px;">. After modifying the schedule, @fig-gradient-descent will update to reflect the new schedule.

::: {#fig-learning-rate}
::: {#div-learning-rate .column-body-outset}
``` {=html}
<script src="learning_rate_schedule.js"></script>
```
:::

An exponential learning rate schedule defined by $\alpha_t = \alpha_0 r^t$ with $r =$ <span id="lr-value">0.999</span> and $\alpha_0 =$ 0.0001.
:::

<script>
    const slider = document.getElementById("lr-slider");
    const value = document.getElementById("lr-value");
    slider.addEventListener("input", function() {
        window.GLOBAL_STATE.lrSchedule = scheduleExponential(0.0001, parseFloat(slider.value), 5000);
            window.dispatchEvent(new Event("lrScheduleChanged"));
        value.textContent = parseFloat(slider.value).toFixed(3);
    });
</script>

# Further Reading

Modern machine learning generally uses a variant of the ADAM optimizer [@Kingma_Ba_2017], which is a variant of gradient descent including something called momentum. For an interactive explainer on momentum-based optimization methods, I highly recomend [@Goh_2017], which has very informative animations on the subject.
